### PR TITLE
Synaptic Partner Documentation

### PR DESCRIPTION
**Pull request by geekswaroop**
@donglaiw please review!

### CODE REVIEW

**Comment by zudi-lin** [comment]
hi @geekswaroop, recently we have updated the whole package to use the **YACS config system** for better reproducibility. 

1. Could you please follow https://zudi-lin.github.io/pytorch_connectomics/build/html/tutorials/cremi.html to update the synaptic partner tutorial? 
2. Please add **the corresponding config yaml file** of synaptic partner prediction to https://github.com/zudi-lin/pytorch_connectomics/tree/master/configs. You may need to debug a little bit. 
3. Besides, please just update the source rst files and do not build the html, otherwise there will be conflicts. 

Thanks!

**Comment by geekswaroop** [comment]
Hi @zudi-lin , sure thing, but I have closely followed https://zudilin.github.io/pytorch_connectomics/build/html/tutorials/cremi.html to write documentation for Synaptic Partners.. 
Are you asking me to include Synaptic Partners in the Synaptic Cleft Detection Docs itself?

**Comment by zudi-lin** [comment]
Hi @geekswaroop, just write a new one. That tutorial is exclusively for the CREMI challenge. For our own connectomics research we usually do the synaptic polarity prediction, which is more informative.

**Comment by geekswaroop** [comment]
I've created a new PR. Please let me know if it needs changes!

**Pull request closed without merging**
