### PR TITLE
Update lucchi.rst

### PR DESCRIPTION
**Pull request by aayushk614**

### CODE REVIEW

**Comment by zudi-lin** [comment]
Hi @aayushk614, could you please also update the corresponding config file at https://github.com/zudi-lin/pytorch_connectomics/tree/master/configs? Just title it as Lucchi-Mitochondria.yaml

**Comment by aayushk614** [comment]
Yeah,
I am working on it. It has to be done in a new file right?

**Comment by zudi-lin** [comment]
Yes, add a new config file. Thanks!

**Comment by aayushk614** [comment]
Alright.

**Pull request merged**
